{% set python_min = "3.11" %}
{% set name = "iris-esmf-regrid" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/esmf-regrid/esmf_regrid-{{ version }}.tar.gz
  sha256: 4288038a226586e7ebcdfd0c4564d4865dfd3f57dc1c086511f13574f59d5b4f


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
  run:
    - python >={{ python_min }}
    - numpy >=1.14
    - scipy
    - cartopy >=0.18
    - esmpy >=7.0
    - iris >=3
    - dask
    - cf-units

test:
  requires:
    - python {{ python_min }}
  imports:
    - esmf_regrid

about:
  home: https://github.com/SciTools/iris-esmf-regrid
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A collection of structured and unstructured ESMF regridding schemes for Iris.
extra:
  recipe-maintainers:
    - jamesp
    - bjlittle
    - stephenworsley
    - zklaus
    - trexfeathers
    - pp-mo
    - HGWright
