{% set name = "iris-esmf-regrid" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SciTools-incubator/iris-esmf-regrid/archive/v{{ version }}.tar.gz
  sha256: 94249b8bdd4a28e102aa380a49535faa312cde89248aacc1e405726baf4dbb54


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<3.9
    - pip
  run:
    - python >=3.6,<3.9
    - numpy
    - scipy
    - cartopy
    - esmpy
    - iris >=3

test:
  imports:
    - esmf_regrid

about:
  home: https://github.com/SciTools-incubator/iris-esmf-regrid
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A collection of structured and unstructured ESMF regridding schemes for Iris.
extra:
  recipe-maintainers:
    - jamesp
    - bjlittle
    - stephenworsley
    - zklaus
