{% set name = "iris-esmf-regrid" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SciTools-incubator/iris-esmf-regrid/archive/v{{ version }}.tar.gz
  sha256: 876a393975ef98549c903db6ee4abb45c41f51c60584df39a4c8a509f0b55c4c


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy
    - cartopy
    - esmpy
    - iris >=3
    - dask
    - cf-units

test:
  imports:
    - esmf_regrid

about:
  home: https://github.com/SciTools-incubator/iris-esmf-regrid
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A collection of structured and unstructured ESMF regridding schemes for Iris.
extra:
  recipe-maintainers:
    - jamesp
    - bjlittle
    - stephenworsley
    - zklaus
    - trexfeathers
