{% set name = "iris-esmf-regrid" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/e/esmf-regrid/esmf_regrid-{{ version }}.tar.gz
  sha256: 37e85a54f7951ec81c7b2fd55be5907793e5894870f78a9e1411fd0b9ed64bfe


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - numpy >=1.14
    - scipy
    - cartopy >=0.18
    - esmpy >=7.0
    - iris >=3
    - dask
    - cf-units

test:
  imports:
    - esmf_regrid

about:
  home: https://github.com/SciTools-incubator/iris-esmf-regrid
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A collection of structured and unstructured ESMF regridding schemes for Iris.
extra:
  recipe-maintainers:
    - jamesp
    - bjlittle
    - stephenworsley
    - zklaus
    - trexfeathers
    - pp-mo
    - HGWright
