{% set python_min = "3.12" %}
{% set name = "iris-esmf-regrid" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/esmf-regrid/esmf_regrid-{{ version }}.tar.gz
  sha256: bc636557b68351d53a92ddef4bd7d9edc98473e16f555562bc519c1bea9e3efa


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=77.0.3
  run:
    - python >={{ python_min }}
    - numpy >=1.14
    - scipy
    - cartopy >=0.18
    - esmpy >=7.0
    - iris >=3
    - dask
    - cf-units

test:
  requires:
    - python {{ python_min }}
  imports:
    - esmf_regrid

about:
  home: https://github.com/SciTools/iris-esmf-regrid
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A collection of structured and unstructured ESMF regridding schemes for Iris.
extra:
  recipe-maintainers:
    - jamesp
    - bjlittle
    - stephenworsley
    - zklaus
    - trexfeathers
    - pp-mo
    - HGWright
